sudo: required
dist: trusty

language: cpp

os: linux

compiler: 
    - gcc

before_install:
    # - sudo apt-get install php5-cli
    - sudo wget https://raw.githubusercontent.com/shengofsun/packages/master/source.list
    - sudo cp source.list /etc/apt/sources.list
    # - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
    # - sudo apt-key add 16126D3A3E5C1192
    - sudo apt-get update -qq
    - sudo apt-get install -qq libboost-all-dev libaio-dev lcov gdb

install:
    - ./run.sh format

before_script:
    - ./run.sh start_zk
    - ulimit -c unlimited -S

script:
    - ./run.sh test

after_script:
    - ./run.sh stop_zk

